name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: cd build
      run: cd build
    - name: cmake ..
      run: cmake ..
    - name: make
      run: make
